import day1_part1 from './day-1/part-1';
import day1_part2 from './day-1/part-2';
import day_2_part_1 from './day-2/part-1';
import day_2_part_2 from './day-2/part-2';
import day_4_part_1 from './day-4/part-1';

console.log('Answers:');
console.log(`----------------`);
console.log('Day 1');
console.log(`----------------`);
console.log(`Part 1 | ${day1_part1}`);
console.log(`Part 2 | ${day1_part2}`);
console.log(`----------------`);
console.log('Day 2');
console.log(`----------------`);
console.log(`Part 1 | ${day_2_part_1}`);
console.log(`Part 2 | ${day_2_part_2}`);
console.log(`----------------`);
console.log('Day 4');
console.log(`----------------`);
console.log(`Part 1 | ${day_4_part_1}`);
